// Player bloomby has the comments in it, see it for help and examples.
// Note that you if you have a -move-stationary animation on a sprite,
// you do NOT need the other four. The goose has all five because it is a
// fallback default.
// You'd only want all 5 if your sprite really has 4 directions AND a separate stationary animation.

const spriteSheetList = [
  {
    type: 'player',
    name: 'bloomby',
    fileName: 'bloomby16.png',
    faces: 'right',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1, // How many frames to extract from the sheet. -1 means all
    animationFrameRate: 10,
    animations: [
      { keyName: 'move-left', start: 12, end: 14, zeroPad: 3, repeat: -1 },
      { keyName: 'move-right', start: 12, end: 14, zeroPad: 3, repeat: -1 },
      { keyName: 'move-back', start: 6, end: 11, zeroPad: 3, repeat: -1 },
      { keyName: 'move-front', start: 0, end: 5, zeroPad: 3, repeat: -1 },
    ],
    // physicsSize maps to sprite.setSize
    // physicsOffset maps to sprite.setOffset
    // If your Sprite has whitespace or just bits that can overlap, use
    // setSize (physicsSize) to make the physics object smaller than the sprite.
    // You can use the setSize (physicsSize) and setOffset to allow the character to overlap the
    // collision blocks slightly. This often makes the most sense for the head to overlap a bit so that "background" blocks (above player) seem more "background"
    // Also use the setSize (physicsSize) to allow the character to fit in the spaces it should, even if the sprite is too big for them.
    // Set physicsSize to 0 to have size === the sprite size.
    physicsSize: {
      // Remember where this starts if you muck with the offset below.
      // If you are having trouble, turn on the debugging on the intro/help screen.
      // This is RELATIVE TO SPRITE SIZE and then gets scaled, so the same numbers on two different
      // sized sprites will not produce the same results!
      // Using a multiplier can help keep it consistent between different sprites,
      // but remember different size sprites will still end up with different end results after multiplication.
      x: 12, // "Width" direction
      y: 14, // "Height" direction
    },
    // DELETE or COMMENT OUT the entire physicsOffset to ignore it and default to object center.
    // physicsOffset: {
    //   x: 25, // left/right aka in relation to width
    //   y: 25,
    // },
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'ChairTwo',
    fileName: 'chair2.png',
    faces: 'right',
    frameWidth: 10,
    frameHeight: 12,
    endFrame: -1, // How many frames to extract from the sheet. -1 means all
    animationFrameRate: 0,
    animations: [
      { keyName: 'move-left', start: 2, end: 2, zeroPad: 3, repeat: -1 },
      { keyName: 'move-right', start: 2, end: 2, zeroPad: 3, repeat: -1 },
      { keyName: 'move-back', start: 1, end: 1, zeroPad: 3, repeat: -1 },
      { keyName: 'move-front', start: 0, end: 0, zeroPad: 3, repeat: -1 },
    ],
    physicsSize: {
      x: 10,
      y: 12,
    },
    displayWidth: 10,
    displayHeight: 12,
  },
  {
    type: 'other',
    name: 'TableOne',
    fileName: 'table1.png',
    faces: 'right',
    frameWidth: 16,
    frameHeight: 10,
    physicsSize: {
      x: 16,
      y: 10,
    },
    displayWidth: 16,
    displayHeight: 10,
  },
  {
    type: 'other',
    name: 'WickedSnailOne',
    fileName: 'WickedSnail1.png',
    faces: 'right',
    frameWidth: 32,
    frameHeight: 32,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 0, zeroPad: 3, repeat: -1 },
    ],
    physicsSize: {
      x: 32,
      y: 32,
    },
    displayWidth: 32,
    displayHeight: 32,
  },
  {
    type: 'other',
    name: 'YellowKey',
    fileName: 'YellowKey.png',
    faces: 'right',
    frameWidth: 9,
    frameHeight: 6,
    physicsSize: {
      x: 9,
      y: 6,
    },
    displayWidth: 9,
    displayHeight: 6,
  },
  {
    type: 'other',
    name: 'RedKey',
    fileName: 'RedKey.png',
    faces: 'right',
    frameWidth: 9,
    frameHeight: 6,
    physicsSize: {
      x: 9,
      y: 6,
    },
    displayWidth: 9,
    displayHeight: 6,
  },
  {
    type: 'other',
    name: 'Whirl',
    fileName: 'Whirl.png',
    faces: 'right',
    frameWidth: 45,
    frameHeight: 45,
    physicsSize: {
      x: 45,
      y: 45,
    },
    displayWidth: 90,
    displayHeight: 90,
    endFrame: -1,
    animationFrameRate: 10,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 15, zeroPad: 3, repeat: -1 },
    ],
  },
  {
    type: 'other',
    name: 'quasar',
    fileName: 'Quasar.png',
    faces: 'right',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1, // How many frames to extract from the sheet. -1 means all
    animationFrameRate: 20,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 17, zeroPad: 2, repeat: -1 },
    ],
    physicsCircle: {
      radius: 4,
    },
    physicsOffset: {
      x: 5,
      y: 5,
    },
    physicsSize: {
      x: 0,
      y: 0,
    },
    displayWidth: 16,
    displayHeight: 16,
    rotatable: true, // For sprites that should rotate to any direction, instead of just the 4
  },
  // laserArrow
  {
    type: 'other',
    name: 'laserArrow',
    fileName: 'LaserArrow2.png',
    faces: 'right',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1, // How many frames to extract from the sheet. -1 means all
    animationFrameRate: 20,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 9, zeroPad: 2, repeat: -1 },
    ],
    physicsCircle: {
      radius: 4,
    },
    physicsOffset: {
      x: 5,
      y: 5,
    },
    physicsSize: {
      x: 0,
      y: 0,
    },
    displayWidth: 16,
    displayHeight: 16,
    rotatable: true, // For sprites that should rotate to any direction, instead of just the 4
  },
  {
    type: 'other',
    name: 'chestFront',
    fileName: 'chest.png',
    frameWidth: 46,
    frameHeight: 43,
    endFrame: 3,
    faces: 'left',
    animationFrameRate: 2,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 2, zeroPad: 3, repeat: -1 },
    ],
    physicsSize: {
      x: 46 * 0.8,
      y: 43 * 0.8,
    },
    displayWidth: 46 * 0.8,
    displayHeight: 43 * 0.8,
  },
  {
    type: 'other',
    name: 'corpse',
    fileName: 'BrokenHeart.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: 1,
    physicsSize: {
      x: 16,
      y: 16,
    },
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'RainbowTileOne',
    fileName: 'RainbowTileOne.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 1,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 7, zeroPad: 3, repeat: -1 },
    ],
    physicsSize: {
      x: 50,
      y: 50,
    },
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'writtenPaper',
    fileName: 'writtenPaper.png',
    frameWidth: 14,
    frameHeight: 14,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 2,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 10, zeroPad: 3, repeat: -1 },
    ],
    physicsSize: {
      x: 14,
      y: 14,
    },
    displayWidth: 14,
    displayHeight: 14,
  },
  {
    type: 'other',
    name: 'Fountain',
    fileName: 'Fountain.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 5,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 10, zeroPad: 3, repeat: -1 },
    ],
    physicsSize: {
      x: 16,
      y: 16,
    },
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'Barricade-RedKey',
    fileName: 'Barricade-RedKey.png',
    faces: 'right',
    frameWidth: 16,
    frameHeight: 16,
    physicsSize: {
      x: 16,
      y: 16,
    },
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'Barricade-YellowKey',
    fileName: 'Barricade-YellowKey.png',
    faces: 'right',
    frameWidth: 16,
    frameHeight: 16,
    physicsSize: {
      x: 16,
      y: 16,
    },
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'Barricade-OrangeKey',
    fileName: 'Barricade-OrangeKey.png',
    faces: 'right',
    frameWidth: 16,
    frameHeight: 16,
    physicsSize: {
      x: 16,
      y: 16,
    },
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'Barricade-GreyKey',
    fileName: 'Barricade-GreyKey.png',
    faces: 'right',
    frameWidth: 16,
    frameHeight: 16,
    physicsSize: {
      x: 16,
      y: 16,
    },
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'Barricade-BlueKey',
    fileName: 'Barricade-BlueKey.png',
    faces: 'right',
    frameWidth: 16,
    frameHeight: 16,
    physicsSize: {
      x: 16,
      y: 16,
    },
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'Barricade-BlackKey',
    fileName: 'Barricade-BlackKey.png',
    faces: 'right',
    frameWidth: 16,
    frameHeight: 16,
    physicsSize: {
      x: 16,
      y: 16,
    },
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'Barricade-PurpleKey',
    fileName: 'Barricade-PurpleKey.png',
    faces: 'right',
    frameWidth: 16,
    frameHeight: 16,
    physicsSize: {
      x: 16,
      y: 16,
    },
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'Barricade-DarkBlueKey',
    fileName: 'Barricade-DarkBlueKey.png',
    faces: 'right',
    frameWidth: 16,
    frameHeight: 16,
    physicsSize: {
      x: 16,
      y: 16,
    },
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'Barricade-LightBlueKey',
    fileName: 'Barricade-LightBlueKey.png',
    faces: 'right',
    frameWidth: 16,
    frameHeight: 16,
    physicsSize: {
      x: 16,
      y: 16,
    },
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'Barricade-PinkKey',
    fileName: 'Barricade-PinkKey.png',
    faces: 'right',
    frameWidth: 16,
    frameHeight: 16,
    physicsSize: {
      x: 16,
      y: 16,
    },
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'Barricade-TurquoiseKey',
    fileName: 'Barricade-TurquoiseKey.png',
    faces: 'right',
    frameWidth: 16,
    frameHeight: 16,
    physicsSize: {
      x: 16,
      y: 16,
    },
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'PurpleRunningRunes',
    fileName: 'purpleRunningRunes.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 5,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 15, zeroPad: 3, repeat: -1 },
    ],
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'redTankSingle',
    fileName: 'redTankSingle.png',
    frameWidth: 46,
    frameHeight: 38,
    endFrame: -1,
    faces: 'left',
    physicsSize: {
      x: 24,
      y: 24,
    },
    displayWidth: 16,
    displayHeight: 16,
    rotatable: true,
  },
  {
    type: 'other',
    name: 'yellowTankSingle',
    fileName: 'yellowTankSingle.png',
    frameWidth: 46,
    frameHeight: 38,
    endFrame: -1,
    faces: 'left',
    physicsSize: {
      x: 46,
      y: 24,
    },
    displayWidth: 16,
    displayHeight: 16,
    rotatable: true,
  },
  {
    type: 'other',
    name: 'BlackWater',
    fileName: 'BlackWater.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 10,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 7, zeroPad: 3, repeat: -1 },
    ],
    physicsSize: {
      x: 50,
      y: 50,
    },
    physicsOffset: {
      x: 22,
      y: 35,
    },
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'BlackFlowingDown',
    fileName: 'BlackFlowingDown.png',
    frameWidth: 32,
    frameHeight: 32,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 10,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 14, zeroPad: 3, repeat: -1 },
    ],
    physicsSize: {
      x: 50,
      y: 50,
    },
    physicsOffset: {
      x: 22,
      y: 35,
    },
    displayWidth: 32,
    displayHeight: 32,
  },
  {
    type: 'other',
    name: 'SkullWink',
    fileName: 'SkullWink.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 8,
    animations: [
      {
        keyName: 'move-stationary',
        start: 0,
        end: 3,
        zeroPad: 3,
        repeat: -1,
        repeatDelay: 10000,
      },
    ],
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'BlueWater',
    fileName: 'BlueWater.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 7,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 7, zeroPad: 3, repeat: -1 },
    ],
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'BlueWaterFlowingDown',
    fileName: 'BlueWaterFlowingDown.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 7,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 7, zeroPad: 3, repeat: -1 },
    ],
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'BlueWaterNorthShore',
    fileName: 'BlueWaterNorthShore.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 7,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 15, zeroPad: 3, repeat: -1 },
    ],
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'BlueWaterSouthShore',
    fileName: 'BlueWaterSouthShore.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 7,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 15, zeroPad: 3, repeat: -1 },
    ],
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'BlueWaterNorthWestShore',
    fileName: 'BlueWaterNorthWestShore.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 7,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 15, zeroPad: 3, repeat: -1 },
    ],
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'BlueWaterNorthEastShore',
    fileName: 'BlueWaterNorthEastShore.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 7,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 15, zeroPad: 3, repeat: -1 },
    ],
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'BlueWaterSouthEastShoreCorner',
    fileName: 'BlueWaterSouthEastShoreCorner.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 7,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 15, zeroPad: 3, repeat: -1 },
    ],
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'BlueWaterSouthWestShoreCorner',
    fileName: 'BlueWaterSouthWestShoreCorner.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 7,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 15, zeroPad: 3, repeat: -1 },
    ],
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'BlueWaterNorthWestShoreCorner',
    fileName: 'BlueWaterNorthWestShoreCorner.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 7,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 15, zeroPad: 3, repeat: -1 },
    ],
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'BlueWaterSouthWestShore',
    fileName: 'BlueWaterSouthWestShore.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 7,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 15, zeroPad: 3, repeat: -1 },
    ],
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'BlueWaterSouthEastShore',
    fileName: 'BlueWaterSouthEastShore.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 7,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 15, zeroPad: 3, repeat: -1 },
    ],
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'BlueWaterWestShore',
    fileName: 'BlueWaterWestShore.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 7,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 15, zeroPad: 3, repeat: -1 },
    ],
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'BlueWaterEastShore',
    fileName: 'BlueWaterEastShore.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 7,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 15, zeroPad: 3, repeat: -1 },
    ],
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'MountainWallSparkleOne',
    fileName: 'MountainWallSparkleOne.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 1,
    animations: [
      {
        keyName: 'move-stationary',
        start: 0,
        end: 4,
        zeroPad: 3,
        repeat: -1,
        repeatDelay: 500,
      },
    ],
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'MountainWallSparkleTwo',
    fileName: 'MountainWallSparkleTwo.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 8,
    animations: [
      {
        keyName: 'move-stationary',
        start: 0,
        end: 8,
        zeroPad: 3,
        repeat: -1,
        repeatDelay: 10000,
      },
    ],
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'SilverSparkleForTree',
    fileName: 'SilverSparkleForTree.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 8,
    animations: [
      {
        keyName: 'move-stationary',
        start: 0,
        end: 8,
        zeroPad: 3,
        repeat: -1,
        repeatDelay: 10000,
      },
    ],
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'GroundSparkleOne',
    fileName: 'GroundSparkleOne.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 1,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 5, zeroPad: 3, repeat: -1 },
    ],
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    type: 'other',
    name: 'GroundSparkleTwo',
    fileName: 'GroundSparkleTwo.png',
    frameWidth: 16,
    frameHeight: 16,
    endFrame: -1,
    faces: 'left',
    animationFrameRate: 1,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 5, zeroPad: 3, repeat: -1 },
    ],
    displayWidth: 16,
    displayHeight: 16,
  },
  {
    // Flaming Goose is the default sprite used whenever a requested sprite cannot be found,
    // so it is set up to fill a lot of roles, but also expected to never look great.
    type: 'other',
    name: 'flamingGoose',
    fileName: 'flamingGoose.png',
    frameWidth: 82,
    frameHeight: 79,
    endFrame: 4,
    faces: 'left',
    animationFrameRate: 5,
    animations: [
      { keyName: 'move-stationary', start: 0, end: 3, zeroPad: 3, repeat: -1 },
      { keyName: 'move-left', start: 0, end: 3, zeroPad: 3, repeat: -1 },
      { keyName: 'move-right', start: 0, end: 3, zeroPad: 3, repeat: -1 },
      { keyName: 'move-back', start: 0, end: 3, zeroPad: 3, repeat: -1 },
      { keyName: 'move-front', start: 0, end: 3, zeroPad: 3, repeat: -1 },
    ],
    physicsSize: {
      x: 82,
      y: 79,
    },
    displayWidth: 16,
    displayHeight: 16,
  },
];

export default spriteSheetList;
