name: Client Build Test

on:
  push:
    branches: [ main ]
    paths:
      - "client/**"
  pull_request:
    branches: [ main ]
    paths:
      - "client/**"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        required: false
        description: 'Manually run test client build'
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json
      - run: npm ci
        working-directory: client
      - run: npm run build
        working-directory: client
