name: Client Build Test

on:
  push:
    branches: [ main ]
    paths:
      - "client/**"
  pull_request:
    branches: [ main ]
    paths:
      - "client/**"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        required: false
        description: 'Manually test run client build'
jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 19
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - run: ./scripts/versionNumberUpdate.sh
      - run: npm ci
      - run: npm run build
