name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        required: false
        description: 'Manually test run Playwright Tests'
jobs:
  test:
    env:
      NODE_ENV: "dev"
      PORT: "8080"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: pnpm i
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Set Version Number
        run: ./scripts/versionNumberUpdate.sh
      - name: Run Server in background
        run: node server/server.js &
      - name: Run Client web server in background
        run: npm run client-no-browser < /dev/null &
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30