name: Server Run Test

on:
  push:
    branches: [ main ]
    paths:
      - "server/**"
  pull_request:
    branches: [ main ]
    paths:
      - "server/**"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        required: false
        description: 'Manually test run server'
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: npm ci
        working-directory: client
      - run: npm ci
        working-directory: server
      - run: node server.js
        working-directory: server
