name: Server Run Test
on:
  push:
    branches: [ main ]
    paths:
      - "server/**"
  pull_request:
    branches: [ main ]
    paths:
      - "server/**"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        required: false
        description: 'Manually test run server'
jobs:
  build:
    env:
      CI_TEST_RUN: "true"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - run: ./scripts/versionNumberUpdate.sh
      - run: npm ci
      - run: node server/server.js
