name: Server Run Test
on:
  push:
    branches: [ main ]
    paths:
      - "server/**"
  pull_request:
    branches: [ main ]
    paths:
      - "server/**"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        required: false
        description: 'Manually test run server'
jobs:
  build:
    env:
      CI_TEST_RUN: "true"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts
          cache: 'pnpm'
      - run: ./scripts/versionNumberUpdate.sh
      - run: pnpm i
      - run: node server/server.js
